version: "3"

networks:
    gocas-mgmt:
      external:
        name: gocas-mgmt

services:
  r2_assembly_coordinator:
    image: 192.168.10.105:5000/r2_assembly_coordinator
    build:
        context: ./Robot2_Coordinator
        dockerfile: Dockerfile
    container_name: r2_assembly_coordinator
    deploy:
        placement:
            constraints:
                - node.hostname==GOCASr2
        resources:
            limits:
                memory: 500M
    networks: 
        - gocas-mgmt
    volumes:
        - /tmp:/tmp

  workertask2:
    image: 192.168.10.105:5000/workertask2
    build:
        context: ./WorkerTask2
        dockerfile: Dockerfile
    container_name: workertask2
    deploy:
        placement:
            constraints:
                - node.hostname==GOCASr2
        resources:
            limits:
                memory: 500M
    volumes:
        - /tmp:/tmp
    environment:
        - PYTHONUNBUFFERED=1

  workertask3:
    image: 192.168.10.105:5000/workertask3
    build:
        context: ./WorkerTask3
        dockerfile: Dockerfile
    container_name: workertask3
    deploy:
        placement:
            constraints:
                - node.hostname==GOCASr2
        resources:
            limits:
                memory: 500M
    volumes:
        - /tmp:/tmp
    environment:
        - PYTHONUNBUFFERED=1

  workertask5:
    image: 192.168.10.105:5000/workertask5
    build:
        context: ./WorkerTask5
        dockerfile: Dockerfile
    container_name: workertask5
    deploy:
        placement:
            constraints:
                - node.hostname==GOCASr2
        resources:
            limits:
                memory: 500M
    volumes:
        - /tmp:/tmp
    environment:
        - PYTHONUNBUFFERED=1

  r2_controller:
    image: 192.168.10.105:5000/r2_controller
    build:
        context: ./RobotControllerMs
        dockerfile: Dockerfile
    container_name: robot2controller
    deploy:
        placement:
            constraints:
                - node.hostname==GOCASr2
        resources:
            limits:
                memory: 500M
    volumes:
        - /tmp:/tmp
        - /sys:/sys
    environment:
        - PYTHONUNBUFFERED=1