version: "3"

networks:
  gocas-mgmt:
    external:
      name: gocas-mgmt

services:
  w1-assembly-coordinator:
    image: 192.168.10.105:5000/w1_assembly_coordinator
    build:
      context: ./Workbench1_Coordinator
      dockerfile: Dockerfile
    container_name: w1_assembly_coordinator
    deploy:
      placement:
          constraints:
              - node.hostname==GOCASw1
      resources:
          limits:
              memory: 500M
    networks: 
      - gocas-mgmt
    volumes:
      - /tmp:/tmp
    
  w1_controller:
    image: 192.168.10.105:5000/w1_controller
    build:
      context: ./Workbench1ControllerMs
      dockerfile: Dockerfile
    container_name: w1controller
    deploy:
      placement:
          constraints:
              - node.hostname==GOCASw1
      resources:
          limits:
              memory: 500M
    volumes:
      - /tmp:/tmp
      - /sys:/sys
    environment:
      - PYTHONUNBUFFERED=1