FROM maven:alpine as builder
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src/ /build/src/
RUN mvn package -DskipTests

FROM arm32v7/openjdk:8-slim
WORKDIR /app
COPY --from=builder /build/target/Workbench2_Coordinator-0.0.1-SNAPSHOT.jar .
ENTRYPOINT [ "java","-jar","Workbench2_Coordinator-0.0.1-SNAPSHOT.jar"]
