version: "3"

networks:
    gocas-mgmt:
      external:
        name: gocas-mgmt

services: 
    r1_assembly_coordinator:
        image: 127.0.0.1:5000/r1_assembly_coordinator
        build:
            context: ./Robot1_Coordinator
            dockerfile: Dockerfile
        container_name: r1_assembly_coordinator
        deploy:
            placement:
                constraints:
                    - node.hostname==Robot1
            resources:
                limits:
                    memory: 500M
        networks: 
            - gocas-mgmt
        volumes:
            - /tmp:/tmp

    workertask1:
        image: 127.0.0.1:5000/workertask1
        build:
            context: ./WorkerTask1
            dockerfile: Dockerfile
        container_name: workertask1
        deploy:
            placement:
                constraints:
                    - node.hostname==Robot1
            resources:
                limits:
                    memory: 500M
        volumes:
            - /tmp:/tmp
        environment:
            - PYTHONUNBUFFERED=1

    workertask4:
        image: 127.0.0.1:5000/workertask4
        build:
            context: ./WorkerTask4
            dockerfile: Dockerfile
        container_name: workertask4
        deploy:
            placement:
                constraints:
                    - node.hostname==Robot1
            resources:
                limits:
                    memory: 500M
        volumes:
            - /tmp:/tmp
        environment:
            - PYTHONUNBUFFERED=1

    r1_controller:
        image: 127.0.0.1:5000/r1_controller
        build:
            context: ./RobotControllerMs
            dockerfile: Dockerfile
        container_name: robot1controller
        deploy:
            placement:
                constraints:
                    - node.hostname==Robot1
            resources:
                limits:
                    memory: 500M
        volumes:
            - /tmp:/tmp
            # - /dev/gpiomem:/dev/gpiomemoc
        # privileged: true
        environment:
            - PYTHONUNBUFFERED=1